vlans:
  - vlan_id: 3001
    name: TechWise_01
    interface: Vlan3001
    prefix: 10.30.01.
    gw_mask: 24
    gw_addr: 10.30.01.1
  - vlan_id: 3002
    name: TechWise_02
    interface: Vlan3002
    prefix: 10.30.02.
    gw_mask: 24
    gw_addr: 10.30.02.1
    
ospf: 
  process: 30
  area: 30 
  
hsrp: 
  group: 10    
