# This example ensures the correct SVIs are configured on every switch
---

- name: Setup VLAN Interfaces on Distribution Switches
  hosts: distribution
  connection: local
  tasks: 
    - name: Create SVI Interface 
      with_items: "{{ vlans }}"
      nxos_config: 
        host: "{{ inventory_hostname }}"
        transport: nxapi 
        lines: 
          - "interface {{ item.interface }}"
        save: yes
    - name: Configure IPv4 Address on SVI
      with_items: "{{ vlans }}"
      nxos_ip_interface:
        host: "{{ inventory_hostname }}"
        state: present
        transport: nxapi
        interface: "{{ item.interface }} "
        addr: "{{ item.prefix }}{{svi_octet}}"
        mask: "{{ item.gw_mask }}"  
    - name: Enable HSRP Feature
      nxos_feature: 
        host: "{{ inventory_hostname }}"
        state: present 
        transport: nxapi
        feature: hsrp
        state: enabled
    - name: Setup HSRP on SVI
      with_items: "{{ vlans }}"
      nxos_hsrp: 
        host: "{{ inventory_hostname }}"
        state: present 
        transport: nxapi
        interface: "{{ item.interface }}"
        group: "{{ hsrp.group }}"
        vip: "{{ item.gw_addr }}"

