# This example ensures the correct VLANs are configured on every switch

---
- hosts: switches
  connection: local
  tasks: 
    - name: configure vlans
      with_items: "{{ vlans }}"
      nxos_vlan:
        host: "{{ inventory_hostname }}"
        vlan_id: "{{ item.vlan_id }}"
        name: "{{ item.name }} "
        state: present
        transport: nxapi
        